### ISSUE TITLE
Protocol message enum contain only 1 line - EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by Snakendead** [alexeyxo/protobuf-swift#123]
#### `.proto` file to reproduce

```
            message SMTag {
                enum Action {
                    ActionSearch = 1;
                } optional Action action = 1;

                optional string text = 2;
            } optional SMTag smtag = 3;


```
#### Description

If message contains enum ONLY with 1 line - we get a Builder error

**Comment by alexeyxo** [comment]
I don't know what going wrong. I think some problem in "swift" compiler. I write simple example without protobuf and he crashed when xcode launches any project:
```swift
class Test {
    enum T:Int32, CustomDebugStringConvertible, CustomStringConvertible{
        case A = 0
        var debugDescription:String { return getDescription() }
        var description:String { return getDescription() }
        private func getDescription() -> String {
            switch self {
            case .A: return ".ActionSearch"
            }
        }
    }
    private(set) var b = T.A
    
}
```

**Comment by alexeyxo** [comment]
Crash was reproduced only if you started UnitTest. Do you seen crash in applications?

**Comment by jirid** [comment]
This is most probably [a bug in the Swift compiler](https://bugs.swift.org/browse/SR-1035). The third workaround from the bug report works well for me, unfortunately it requires manual edits to the generated Swift file.
Even though the bug is still open, I was not able to reproduce it in Xcode 7.3.1 with Swift 2.2.1, therefore it might have been fixed.
