### ISSUE TITLE
misleading README instructions

### ISSUE THREAD

**Issue by carocad** [alexeyxo/protobuf-swift#182]
Hi Alexey,
First of all thanks for this wonderful library. I am only starting to get to explore it so I just have a little documentation bug to report.

#### Description

In the README and in the website, it says "Add ./src/ProtocolBuffers/ProtocolBuffers.xcodeproj in your project." which according to the source code, is wrong since there is no such `src` directory.
I am actually not entirely sure if you meant `plugin/PBCompiler/PBCompiler.xcodeproj` or `plugin/ProtocolBuffers/ProtocolBuffers.xcodeproj`.

I got quite confuse about which one should I add since I am quite a beginner. Another thing that I would like to know is if I can run `protobuf-swift` on a Linux machine or does it have to be a Mac OS?

Thanks in advance

**Comment by jabwd** [comment]
I have been using the code on Linux, though I'm considering replacing it with something else at this point. Since the upgrade to Swift3 Linux is no longer compatible with this project, which I think is largely Apple's fault. 

Things that work on OSX with the migration assistant simply are false on Linux, and most likely the patch I'm creating to work around this will break when 3.1 comes out.

The other option I have is using a simpler decoder/encoder which largely would be the same amount of boiler plate code anyway but it'd mean rewriting my codebase.

**Comment by alexeyxo** [comment]
@carocad I have a bug reports about use protobuf-swift on Linux. I think, I can seen the problems today.

**Comment by alexeyxo** [comment]
```
Compile Swift Module 'ProtocolBuffers' (23 sources)
/home/ubuntu/protobuf-swift/Source/RingBuffer.swift:21:51: error: cannot convert value of type 'Data' to type 'NSData' in coercion
    return UnsafeMutablePointer<UInt8>(mutating: (data as NSData).bytes.bindMemory(to: UInt8.self, capacity: data.count))
                                                  ^~~~
/home/ubuntu/protobuf-swift/Source/RingBuffer.swift:25:50: error: cannot convert value of type 'Data' to type 'NSData' in coercion
    return UnsafeMutablePointer<Int8>(mutating: (data as NSData).bytes.bindMemory(to: Int8.self, capacity: data.count))
                                                 ^~~~
/home/ubuntu/protobuf-swift/Source/RingBuffer.swift:69:46: error: cannot convert value of type 'Data' to type 'NSData' in coercion
            memcpy(pointer + Int(position), (input as NSData).bytes + Int(aOffset), Int(totalWritten))
                                             ^~~~~
/home/ubuntu/protobuf-swift/Source/RingBuffer.swift:95:37: error: cannot convert value of type 'Data' to type 'NSData' in coercion
        memcpy(pointer + position, (input as NSData).bytes + Int(aOffset), Int(written))
                                    ^~~~~
/home/ubuntu/protobuf-swift/Source/AbstractMessage.swift:234:21: warning: result of call to 'read(_:maxLength:)' is unused
        inputStream.read(pointer, maxLength: Int(rSize))
                    ^   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
<unknown>:0: error: build had 1 command failures
error: exit(1): /home/ubuntu/swift-3.0-RELEASE-ubuntu14.04/usr/bin/swift-build-tool -f /home/ubuntu/protobuf-swift/.build/debug.yaml
```

**Comment by jabwd** [comment]
This is the work around I used to get it to compile, I have yet to test it against my production code as I need to migrate it to Swift3 as well:

`let ptr = UnsafeMutablePointer<UInt8>.allocate(capacity: data.count)`
	`defer { ptr.deinitialize(count: data.count);ptr.deallocate(capacity: data.count) }`
	`data.copyBytes(to: ptr, count: data.count)`
	`return ptr`

Probably a smarter way of doing this, but I call Swift3 the pointer-fuckup since all of this was easier to begin with in Swift2.

**Comment by jabwd** [comment]
I will look tomorrow into creating a properly working patch, the workaround I posted here earlier doesn't seem to do jack shit, but I have been reading more into how they changed the pointers in Swift3 so who knows. If I can create a proper patch I'll create a pull request.

**Comment by alexeyxo** [comment]
Done.

**Comment by alexeyxo** [comment]
[Installation instruction](https://github.com/alexeyxo/protobuf-swift#how-to-install-protobuf-compiler-on-linuxubuntu-1404)
