### ISSUE TITLE
Compile fails after following installation instructions

### ISSUE THREAD

**Issue by dfclark** [alexeyxo/protobuf-swift#68]
Hi, and thanks for this project.  I followed the installation instructions in the README file, including adding the xcodeproj file into my Xcode workspace.  Everything seems to have built as it was supposed to.  Ran protoc to compile my proto file, and added the output swift file into my project.  But now the compile fails on the "import ProtocolBuffers" line in that output file.   Using Xcode 6.3.2, compiling for iOS 8.  Included a screen shot showing the Xcode issue.

Do you have any ideas about what's missing? 
Thanks
Don

![gpb issue](https://cloud.githubusercontent.com/assets/9804821/8027138/e6bd37d6-0d5e-11e5-9af7-74bb2f90a1bb.png)

**Comment by jamesweb1** [comment]
Did you add ./src/ProtocolBuffers/ProtocolBuffers.xcodeproj in your project? You need to let Xcode know where the ProtocolBuffers is. However, I use Cocoapods to install this to my project, and it works fine for me. You can fine it here: https://cocoapods.org Following is you Podfile: 
```
use_frameworks!
pod 'ProtocolBuffers-Swift`
```
After you creating the Podfile in the root of your project, simply run ```pod install```. Now, you can use the module. Remember, you should open "XXX.xcworkspace" instead of "XXX. xcodeproj" after run ```pod install```.

**Comment by dfclark** [comment]
Hello Alexey,

Yes, I had added ./src/ProtocolBuffers/ProtocolBuffers.xcodeproj to my workspace, made no difference.  But adding the pod reference to my podfile worked!

Thanks
Don

--
Don Clark
don_clark@onsetcomp.com
Mobile - 508.564.1278
Office - 508.743.3392
Fax - 904.261.9976

**Comment by alexeyxo** [comment]
I think, You don't added  "Linked Frameworks and Libraries" in project settings.

**Comment by dfclark** [comment]
I think you are right!  But the pod solution is probably better in the long run anyway.

Thanks again

--
Don Clark
